name: format-lint

on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
    paths:
      - "src/**"
      - "safari/**"
      - "build.mjs"
      - "tests/**"
      - "package.json"
      - "package-lock.json"
      - "scripts/**"
      - ".github/workflows/scripts/**"
      - ".prettierrc"
      - ".eslintrc.json"
      - ".prettierignore"
      - ".github/workflows/format-lint.yml"
  push:
    branches:
      - "master"
    paths:
      - "src/**"
      - "safari/**"
      - "build.mjs"
      - "tests/**"
      - "package.json"
      - "package-lock.json"
      - "scripts/**"
      - ".github/workflows/scripts/**"
      - ".prettierrc"
      - ".eslintrc.json"
      - ".prettierignore"
      - ".github/workflows/format-lint.yml"

jobs:
  format:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 22
      - run: npm ci
      - run: npm run pretty:check

  lint:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 22
      - run: npm ci
      - run: npm run lint
